services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    user: "0:0" 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD} # Match your appsettings.json
    ports:
      - "1433:1433"

  api:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5214:8080"
      # - "7214:7214"
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - AuthTokens__ClientSecret=${AuthTokens__ClientSecret}
      - AuthTokens__MasterToken=${AuthTokens__MasterToken}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Key=${JWT_KEY}
      - Storage__ConnectionString=${Storage__ConnectionString}
      - Storage__Container=${Storage__Container}
      - Steam__Key=${STEAM_KEY}
      - STRIPE__SECRET=${STRIPE_SECRET}
      # - ASPNETCORE_URLS=https://+:7214;http://+:8080
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${Certificate_Pass}
    depends_on:
      - db
    # volumes:
      # - ./https:/https:ro
    develop:
      watch:
        - action: rebuild
          path: ./Backend
          # Triggers a full rebuild if you change .csproj or .sln
        - action: sync
          path: ./Backend
          target: /src

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_STRIPE_PUBLISH=${STRIPE_PUBLISH}
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/