@DecsPager_HostAddress = http://localhost:5214

GET {{DecsPager_HostAddress}}/players?limit=1
Accept: application/json

###
GET {{DecsPager_HostAddress}}/players/76561198213433994
#76561198213433993
Accept: application/json

###
GET {{DecsPager_HostAddress}}/jobs/
Accept: application/json

###

GET {{DecsPager_HostAddress}}/jobs/30
Accept: application/json

###

POST {{DecsPager_HostAddress}}/players/dump
Accept: application/json

###

GET {{DecsPager_HostAddress}}/jobs/38/download
Accept: application/json


###
GET {{DecsPager_HostAddress}}/players/search?search=Tom
Accept: application/json

###
POST {{DecsPager_HostAddress}}/Auth/Token?name=api-client&group=police&perms=write
X-Auth-Secret: RCONPASS1234
Content-Type: application/json

###
POST {{DecsPager_HostAddress}}/players/76561198213433993/updateWhitelisting
Content-Type: application/json
Authorization: Bearer 
{
  "steamId": "76561198213433993",
  "updates": {
    "additionalProperty": "{ncalevel: '2'}"
  }
}