/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Jobs
         * @description Retrieve all jobs as per params
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    statuses?: string;
                    limit?: number | string;
                    offset?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a Job
         * @description Retrieve a job by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplcate Job
         * @description Create a new job with the same details as this job
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a Job
         * @description Cancel a job that hasn't been completed yet
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset / Restart a Job
         * @description Reset a failed Job or Restart a completed job. Required Job ID.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Priority of Job
         * @description Set the job to be either Priority or Not
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/manualComplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Manual as Completed
         * @description Set the Manual Payload entry as complete
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a Jobs File
         * @description Download a file associated with a job. Requires a job ID.
         */
        get: {
            parameters: {
                query?: {
                    direct?: boolean;
                };
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export All Player Data
         * @description Creates a job to export all player data into a CSV for download. Returns Job ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export A Players Data
         * @description Creates a job to export a players data into a CSV for download. Returns Job ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Players
         * @description Fetches a partial profile of all players. Optional Params, Limit, Offset, Search (Name, Aliases, ID, SteamID)
         */
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                    offset?: number | string;
                    search?: string;
                    factions?: string;
                    orderby?: string;
                    direction?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedRecordOfPlayer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get A Player
         * @description Fetches a full profile including housing, vehicles, and gang membership using the SteamID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/updateWhitelisting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a Players Whitelisting
         * @description Update a Faction related players ranks. Requires table of ranks to update and a correct JWT Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WhitelistUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/updaterank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a Player Rank
         * @description Update a Faction related players rank. Requires ID, Rank Name, New Rank Level and a correct JWT Token
         */
        post: {
            parameters: {
                query: {
                    rank: string;
                    newRank: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateRank"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export All Player Data
         * @description Creates a job to export all player data into a CSV for download. Returns Job ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export A Players Data
         * @description Creates a job to export a players data into a CSV for download. Returns Job ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logging/GetLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get A Players Logs
         * @description Get a Players Logs, Requires SteamID, Staff JWT Token and Optionaly Incoming or Outgoing Logs. Default All
         */
        get: {
            parameters: {
                query: {
                    id: string;
                    search?: string;
                    type?: string;
                    offset?: number | string;
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayerLogs"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a JWT Token
         * @description Refresh a JWT Token. Requires JWT Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login to a User Account. Requires Username and Password
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/steamLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Steam Login */
        get: {
            parameters: {
                query?: {
                    currentUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Found */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/steamCallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Steam Callback */
        get: {
            parameters: {
                query?: {
                    currentUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout a User Account. Wipes the GUID Cookie
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/createUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a User
         * @description Create a User. Requires a Vaid JWT Token
         */
        post: {
            parameters: {
                query: {
                    ID: string;
                    username: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/deleteUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a User
         * @description Delete a User. Requires a Valid JWT Token
         */
        post: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/adminResetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Users Password
         * @description Reset a Users Password. Requires a Valid JWT Token
         */
        post: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset Password Without Old Password.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPassword"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/changePassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change User Password
         * @description Change a Users Password. Requires a Valid JWT Token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePassword"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Groups
         * @description Get all active Groups. Optional Params: Limit, Offset, Search (Name, Members, Tag, ID)
         */
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                    offset?: number | string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedRecordOfGangs"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a Gang
         * @description Fetches a full profile including housing using the Gang ID, Name or Tag.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export All Groups Data
         * @description Creates a job to export all Groups data into a CSV for download. Returns Job ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export A Groups Data
         * @description Creates a job to export a Groups data into a CSV for download. Returns Job ID
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Get all stats displayed on the dashbaord stats
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Products
         * @description Get a list of all items available on the shop
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    orderby?: string;
                    direction?: string;
                    limit?: number | string;
                    offset?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedRecordOfShopProduct"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a Specific Product
         * @description Get a specific Item using the Item ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShopProduct"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Orders
         * @description Get a list of all Orders
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    limit?: number | string;
                    offset?: number | string;
                    orderby?: string;
                    direction?: string;
                    adminMode?: boolean;
                    statuses?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedRecordOfOrder"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/order/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a Specific Order
         * @description Get a specific Item using the Order Id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderLong"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/productCategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Product Categories
         * @description Get a list of all Product Categories
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShopCategory"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/product/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a Product
         * @description Update an existing product in the shop
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShopProduct"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/product/{id}/toggleActive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Product Active Status
         * @description Toggle the active status of a product
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/category/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a Category
         * @description Update an existing category in the shop
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShopCategory"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/category/{id}/toggleActive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Category Active Status
         * @description Toggle the active status of a category
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/create-checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCheckoutSessionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/session-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    session_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutSessionStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChangePassword: {
            oldPassword: string;
            newPassword: string;
            confirmNewPassword: string;
        };
        CheckoutSessionStatusResponse: {
            status: null | string;
            paymentStatus: null | string;
            data: null | {
                [key: string]: string;
            };
            /** Format: int32 */
            orderId: null | number | string;
            basket: null | components["schemas"]["ShopProduct"][];
            /** Format: int32 */
            jobId: null | number | string;
        };
        CreateCheckoutSessionRequest: {
            basket: components["schemas"]["ShopProduct"][];
            purchaserId: string;
            receiverId: string;
        };
        CreateCheckoutSessionResponse: {
            clientSecret: string;
        };
        DashbaordTopAssets: {
            name?: string;
            playerId?: string;
            /** Format: int32 */
            houses?: number | string;
            /** Format: int32 */
            vehicles?: number | string;
            /** Format: int32 */
            ground?: number | string;
            /** Format: int32 */
            air?: number | string;
            /** Format: int32 */
            total?: number | string;
        };
        DashboardGroupStats: {
            /** Format: int32 */
            total?: number | string;
            /** Format: int32 */
            active?: number | string;
            /** Format: int32 */
            inactive?: number | string;
            /** Format: int64 */
            totalBank?: number | string;
        };
        DashboardHousingStats: {
            /** Format: int32 */
            total?: number | string;
            /** Format: int32 */
            civilian?: number | string;
            /** Format: int32 */
            group?: number | string;
            /** Format: int32 */
            mortgage?: number | string;
        };
        DashboardJobStats: {
            /** Format: int32 */
            total?: number | string;
            /** Format: int32 */
            complete?: number | string;
            /** Format: int32 */
            pending?: number | string;
            /** Format: int32 */
            failed?: number | string;
            /** Format: int32 */
            processing?: number | string;
            /** Format: int32 */
            cancelled?: number | string;
        };
        DashboardPlayerStats: {
            /** Format: int32 */
            total?: number | string;
            /** Format: int32 */
            police?: number | string;
            /** Format: int32 */
            policeCommand?: number | string;
            /** Format: int32 */
            tfu?: number | string;
            /** Format: int32 */
            nca?: number | string;
            /** Format: int32 */
            npas?: number | string;
            /** Format: int32 */
            mpu?: number | string;
            /** Format: int32 */
            polAcad?: number | string;
            /** Format: int32 */
            medics?: number | string;
            /** Format: int32 */
            medicsCommand?: number | string;
            /** Format: int32 */
            hems?: number | string;
            /** Format: int32 */
            hart?: number | string;
            /** Format: int32 */
            medAcad?: number | string;
            /** Format: int32 */
            ion?: number | string;
            /** Format: int32 */
            ionCommand?: number | string;
            /** Format: int32 */
            delta?: number | string;
            /** Format: int32 */
            um?: number | string;
            /** Format: int32 */
            iaf?: number | string;
            /** Format: int32 */
            ionAcad?: number | string;
            /** Format: int64 */
            totalBank?: number | string;
        };
        DashboardStats: {
            player?: components["schemas"]["DashboardPlayerStats"];
            group?: components["schemas"]["DashboardGroupStats"];
            user?: components["schemas"]["DashboardUserStats"];
            job?: components["schemas"]["DashboardJobStats"];
            jobs?: components["schemas"]["PaginatedRecordOfJob"];
            vehicle?: components["schemas"]["DashboardVehicleStats"];
            housing?: components["schemas"]["DashboardHousingStats"];
            top?: components["schemas"]["DashboardTopStats"];
        };
        DashboardTopMoney: {
            name?: string;
            playerId?: string;
            /** Format: int64 */
            bank?: number | string;
            /** Format: int64 */
            cash?: number | string;
            /** Format: int64 */
            total?: number | string;
        };
        DashboardTopPlaytime: {
            name?: string;
            playerId?: string;
            /** Format: int32 */
            civilian?: number | string;
            /** Format: int32 */
            police?: number | string;
            /** Format: int32 */
            medic?: number | string;
            /** Format: int32 */
            ion?: number | string;
            /** Format: int32 */
            total?: number | string;
        };
        DashboardTopStats: {
            assets?: components["schemas"]["DashbaordTopAssets"];
            money?: components["schemas"]["DashboardTopMoney"];
            playtime?: components["schemas"]["DashboardTopPlaytime"];
        };
        DashboardUserStats: {
            /** Format: int32 */
            total?: number | string;
            /** Format: int32 */
            active?: number | string;
            /** Format: int32 */
            inactive?: number | string;
        };
        DashboardVehicleStats: {
            /** Format: int32 */
            total?: number | string;
            /** Format: int32 */
            civilian?: number | string;
            /** Format: int32 */
            ion?: number | string;
            /** Format: int32 */
            car?: number | string;
            /** Format: int32 */
            air?: number | string;
            /** Format: int32 */
            impounded?: number | string;
        };
        GangMember: {
            name: string;
            id: string;
            /** Format: int32 */
            rank: number | string;
        };
        Gangs: {
            id: string;
            name: string;
            members: components["schemas"]["GangMember"][];
            leader: string;
            tag: string;
            bank: string;
        };
        Job: {
            /** Format: int32 */
            id: number | string;
            type: string;
            status: string;
            result: string;
            payload: string;
            priority: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            permissions: components["schemas"]["Permissions"];
        };
        Order: {
            /** Format: int32 */
            id: number | string;
            purchaserId: string;
            receiverId: string;
            basket: components["schemas"]["ShopProduct"][];
            status: string;
            paymentStatus: string;
            /** Format: int32 */
            amountPence: number | string;
            currency: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderLong: {
            /** Format: int32 */
            id: number | string;
            purchaserId: string;
            receiverId: string;
            basket: components["schemas"]["ShopProduct"][];
            status: string;
            paymentStatus: string;
            paymentMethod: string;
            stripeCheckoutSessionId: string;
            stripePaymentIntentId: string;
            /** Format: int32 */
            amountPence: number | string;
            currency: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            job: components["schemas"]["Job"];
        };
        PaginatedRecordOfGangs: {
            /** Format: int32 */
            totalRows: number | string;
            data: components["schemas"]["Gangs"][];
        };
        PaginatedRecordOfJob: {
            /** Format: int32 */
            totalRows: number | string;
            data: components["schemas"]["Job"][];
        };
        PaginatedRecordOfOrder: {
            /** Format: int32 */
            totalRows: number | string;
            data: components["schemas"]["Order"][];
        };
        PaginatedRecordOfPlayer: {
            /** Format: int32 */
            totalRows: number | string;
            data: components["schemas"]["Player"][];
        };
        PaginatedRecordOfShopProduct: {
            /** Format: int32 */
            totalRows: number | string;
            data: components["schemas"]["ShopProduct"][];
        };
        Permissions: {
            admin: {
                [key: string]: number | string;
            };
        };
        Player: {
            id: string;
            name: string;
            playerId: string;
            cash: string;
            bankacc: string;
            adminLevel: string;
            copLevel: string;
            ionLevel: string;
            medicLevel: string;
            /** Format: date-time */
            lastSeen: string;
            /** Format: date-time */
            insertTime: string;
        };
        PlayerLogs: {
            /** Format: int32 */
            id?: number | string;
            eventType?: string;
            playerId?: string;
            performedBy?: string;
            targetName?: string;
            performedByName?: string;
            details?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ResetPassword: {
            password: string;
            confirmPassword: string;
        };
        ShopCategory: {
            /** Format: int32 */
            id: number | string;
            nameId: string;
            name: string;
            description: string;
            /** Format: int32 */
            sortingOrder: number | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ShopProduct: {
            /** Format: int32 */
            id?: number | string;
            nameId?: string;
            categoryId?: string;
            name?: string;
            description?: string;
            /** Format: int32 */
            pricePence?: number | string;
            currency?: string;
            fulfilmentMode?: string;
            isActive?: boolean;
            /** Format: int32 */
            sortingOrder?: number | string;
            paramsJson?: Record<string, never>[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int32 */
            quantity?: null | number | string;
            isGift?: null | boolean;
            receiverId?: null | string;
            receiverName?: null | string;
        };
        UpdateRank: {
            id: string;
            name: string;
            rankName: string;
            oldValue: string;
            newValue: string;
            outcome: string;
        };
        WhitelistUpdateRequest: {
            steamId: string;
            updates: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
